//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.SpringSalud_produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_IT_SALUDASIGNARMEDICOINGRESO
    {
        public string UnidadReplicacion { get; set; }
        public int IdOrdenAtencion { get; set; }
        public int LineaOrdenAtencion { get; set; }
        public Nullable<int> EpisodioClinico { get; set; }
        public int IDMEDICO { get; set; }
        public int IdPaciente { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> Fechacreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> INDICADORPROCESADO { get; set; }
        public Nullable<System.DateTime> FECHAPROCESADO { get; set; }
    }
}
