//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.SpringSalud_produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SS_HCE_VisorEmergencia
    {
        public string CitaFecha { get; set; }
        public string CitaHora { get; set; }
        public string Origen { get; set; }
        public string NombreEspecialidad { get; set; }
        public string TipoPacienteNombre { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> TipoHospitalizacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string Cama { get; set; }
        public string TipoOrdenAtencionNombre { get; set; }
        public string CodigoHC { get; set; }
        public string CodigoHCAnterior { get; set; }
        public string PacienteNombre { get; set; }
        public string MedicoNombre { get; set; }
        public int IdOrdenAtencion { get; set; }
        public int IdHospitalizacion { get; set; }
        public Nullable<int> Modalidad { get; set; }
        public int IndicadorSeguro { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> TipoPaciente { get; set; }
        public Nullable<int> TipoAtencion { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdEmpresaAseguradora { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public string Compania { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> EstadoEpiAtencion { get; set; }
        public string PersonaAnt { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string NivelInstruccion { get; set; }
        public string Direccion { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public string LugarNacimiento { get; set; }
        public string CodigoPostal { get; set; }
        public string Provincia { get; set; }
        public string Departamento { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string EsPaciente { get; set; }
        public string EsEmpresa { get; set; }
        public string Pais { get; set; }
        public string UnidadReplicacionEC { get; set; }
        public string EstadoPersona { get; set; }
    }
}
