//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.SpringSalud_produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SS_CC_CitasSpring
    {
        public string Compania { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> Medico { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public int IdHorario { get; set; }
        public string Documento { get; set; }
        public string NombreCompleto { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaCita { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public long IdTransaccion { get; set; }
        public string UnidadReplicacion { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdCita { get; set; }
        public Nullable<int> TipoPaciente { get; set; }
        public string CodigoOAM { get; set; }
        public string CodigoIAFAS { get; set; }
        public Nullable<int> IdAseguradora { get; set; }
        public string TipDocEmpleadora { get; set; }
        public string NumDocEmpleadora { get; set; }
        public string NombreEmpleadora { get; set; }
        public string CodigoPoliza { get; set; }
        public string CodigoPlan { get; set; }
        public string TipoCobertura { get; set; }
        public string SubTipoCobertura { get; set; }
        public string CodigoCobertura { get; set; }
        public string NombreCobertura { get; set; }
        public string TipoComprobante { get; set; }
        public string SerieComprobante { get; set; }
        public string SerieCobranza { get; set; }
        public string BancoCobranza { get; set; }
        public string CuentaBancaria { get; set; }
        public string NumeroTarjeta { get; set; }
        public Nullable<int> MultiSitedsIdEmpleadora { get; set; }
        public Nullable<int> IndicadorCobrado { get; set; }
        public Nullable<int> IndicadoSiteds { get; set; }
        public Nullable<int> EstadoAutoAdmision { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string CodigoOA { get; set; }
        public Nullable<int> IdClienteFacturacion { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<int> IndModalidad { get; set; }
        public byte[] FirmaPaciente { get; set; }
        public Nullable<int> IndFirma { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public string DireccionFiscal { get; set; }
        public string CorreoElectronico { get; set; }
    }
}
