//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.SpringSalud_produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SS_HCE_VisorDiagnostico
    {
        public string TAB { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public int IdConsultaExterna { get; set; }
        public int iddiagnostico { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string Nombre { get; set; }
        public string CodigoDiagnostico { get; set; }
        public string TipoDiagnostico { get; set; }
        public string TipoAntecedente { get; set; }
        public int IndicadorAntecedente { get; set; }
        public string DetalleDiagnostico { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string documento { get; set; }
        public string tipodocumento { get; set; }
    }
}
