//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.SpringSalud_produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SS_HCE_VisorProcedimientoInforme
    {
        public string LinkInforme { get; set; }
        public string codigoOA { get; set; }
        public string DesEspecialidad { get; set; }
        public string Sucursal { get; set; }
        public string documento { get; set; }
        public string tipodocumento { get; set; }
        public int IdOrdenAtencion { get; set; }
        public int Linea { get; set; }
        public string Componente { get; set; }
        public string Observacion { get; set; }
        public int IdProcedimiento { get; set; }
        public int IdInforme { get; set; }
        public string Nombre { get; set; }
        public string RutaInforme { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> TipoOrdenAtencion { get; set; }
        public Nullable<int> estdetalle { get; set; }
        public Nullable<int> EstadoDocumento { get; set; }
        public Nullable<System.DateTime> FechaDetalle { get; set; }
        public Nullable<int> SituacionInterfase { get; set; }
        public Nullable<int> GrupoInterfase { get; set; }
        public Nullable<int> Medico { get; set; }
        public Nullable<int> Especialidad { get; set; }
    }
}
