//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.SpringSalud_produccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SS_HCE_VisorReceta
    {
        public string TAB { get; set; }
        public string documento { get; set; }
        public string tipodocumento { get; set; }
        public int IdConsultaExterna { get; set; }
        public int Secuencial { get; set; }
        public Nullable<int> IdOrdenAtencion { get; set; }
        public Nullable<int> LineaOrdenAtencion { get; set; }
        public string TipoComponente { get; set; }
        public string Componente { get; set; }
        public Nullable<int> UnidadMedida { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> Forma { get; set; }
        public Nullable<int> Via { get; set; }
        public decimal Dosis { get; set; }
        public decimal DiasTratamiento { get; set; }
        public decimal Frecuencia { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string Componente_Nombre { get; set; }
        public string SubFamilia { get; set; }
        public string DCI { get; set; }
        public string Familia { get; set; }
        public string FAM { get; set; }
        public string linea { get; set; }
        public string LIN { get; set; }
        public Nullable<int> IndicadorEPS { get; set; }
        public Nullable<int> IndicadorCobrado { get; set; }
        public string Sucursal { get; set; }
        public string DesVia { get; set; }
        public string DesUnidad { get; set; }
        public string IndicacionesEsp { get; set; }
    }
}
