//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.WEB_ERPSALUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_OrdenInterQuiruComponentes
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Sucursal { get; set; }
        public string CodigoMedi { get; set; }
    }
}
