//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalSISWS.Models.WEB_ERPSALUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_HC_OrdenIntervencionQuirurgicaCab_FE
    {
        public string UnidadReplicacion { get; set; }
        public long IdEpisodioAtencion { get; set; }
        public int IdPaciente { get; set; }
        public int EpisodioClinico { get; set; }
        public Nullable<int> IdCirugia { get; set; }
        public string CirugiaCompleja { get; set; }
        public string DuracionAprox { get; set; }
        public string TipoDeHospitalizacion { get; set; }
        public string DiasAproximados { get; set; }
        public string TipoAnastesia { get; set; }
        public string NumeroAyudantes { get; set; }
        public string NumeroInstrumentos { get; set; }
        public string EquipoHumano { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Accion { get; set; }
        public string Version { get; set; }
        public string OrdIntNinguna { get; set; }
        public string OrdIntOtro { get; set; }
        public string OrdAnastesiologo { get; set; }
        public string TiempoEnfermedad { get; set; }
        public Nullable<System.DateTime> FechaIntervencion { get; set; }
    }
}
